#!/bin/python
import os
import random


with open(os.path.expanduser("~/tasklist"), "r") as file:
    tasks = [x.strip() for x in file.readlines()]

selection = random.choice(tasks)
print(selection)

