#!/bin/sh


case $1 in
    1) notify-send "$(nvidia-smi)" ;;
    2) setsid -f "$TERMINAL" -e vim ~/.config/scripts/blocks/sb-gpuT ;;
    3) setsid -f "$TERMINAL" -e nvtop ;;
esac


[ -n "$1" ] || nvidia-smi -q -d TEMPERATURE | sed -n '/GPU Current Temp/ s/.*:\s\([0-9]\{2\}\)\s/🔥GPU:+\1°/pg'
