#!/bin/bash

# xrandr --output DisplayPort-2 --set TearFree on --primary --output DisplayPort-0 --set TearFree on --left-of DisplayPort-2 &
xrandr --output DisplayPort-2 --set TearFree on --primary --output DisplayPort-0 --set TearFree on --left-of DisplayPort-2 --output HDMI-A-0 --set TearFree on --right-of DisplayPort-2 &

