#!/bin/sh

file="$(fd -H -E 'node_modules/' -E 'Cache/' -E '.cache/' -E '.local/' -E 'H/' -E '.rustup/' -E '*.pyc' -E '.git/' \
    -tf --no-ignore -c always --search-path "$HOME/" | \
    fzf --reverse --height=20 --ansi)"

ext="${file##*.}"
dir="${file%/*}"

[ "$file" = "" ] && exit 1

case "$ext" in
    pdf)
        zathura "$file"
        ;;
    *)
        vim -c "cd! $dir" "$file"
        ;;
esac
