#!/bin/sh

if [ -z "$1" ]; then
	echo "Script needs an argument."
	exit 1
fi

fname="${1%.*}"

# Trim the path from the file name.
title_w_ext="${1##*/}"
# Trim the extension from the file name.
title="${title_w_ext%.*}"

{
cat << _EOF_
<!doctype html>
<html lang="es">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="shortcut icon" href="./images/favicon.ico" type="image/x-icon">
	<link rel="stylesheet" type="text/css" media="screen" href="normalize.css">
	<link rel="stylesheet" type="text/css" media="screen" href="markdown.css">
	<title>${title}</title>
</head>
<body>
_EOF_

/usr/bin/markdown "$1"

cat << _EOF_
</body>
</html>
_EOF_
} > "${fname}.htm"

# This will open your .htm file again if it is not on the current tab.
# Check the window list for the html file to already be open and if not then launch it.
wmctrl -l | grep -q "$title - Mozilla Firefox" || firefox "${fname}.htm" 2>/dev/null &

# This has been refreshing random web pages I have open and has not worked consistently.
# Refresh the page.
# xdotool search --name "$title - Mozilla Firefox" key ctrl+r
