#!/bin/sh

init="$(($(cat /sys/class/net/eno1/statistics/rx_bytes | paste -sd '+')))"

printf "Recording bandwidth."

read -r lol

fin="$(($(cat /sys/class/net/eno1/statistics/rx_bytes | paste -sd '+')))"

printf "%4sB of bandwidth used. \\n" $(numfmt --to=iec $(($fin-$init)))
