#!/bin/sh

[ -n "$1" ] && d="$(date +%_d | sed -n 's/\s*//p')"

case $1 in
    1) notify-send "$(cal | sed 's/\s\?\(\<'"$d"'\>\)\s\?/(\1)/g')" ;;
    2) setsid -f "$TERMINAL" -e $EDITOR ~/.config/scripts/blocks/sb-calendar ;;
    3) notify-send "$(cal -3 | sed 's/\(.\{21\}\)\s\('"$d"'\)\s\(.\{21\}\)/\1(\2)\3/g'
)" ;;
esac

[ -n "$1" ] || echo "$(date '+%a %b %d,%l:%M %P')"
