#!/bin/sh


case $1 in
    1) notify-send "10 Most CPU Usage
PROGRAM         %CPU" "$(ps axch -o cmd:15,%cpu --sort -%cpu | head)" ;;
    2) setsid -f "$TERMINAL" -e vim ~/.config/scripts/blocks/sb-cpuT ;;
    3) setsid -f "$TERMINAL" -e htop ;;
esac


[ -n "$1" ] || sensors | sed -n '/Package/ s/^.*\s\(\+[0-9]\{2\}.[0-9].\{2\}\)\s.*$/🔥CPU:\1/p'
#sensors -u | sed -n '/Package id/,/Core 0/ {/input/ s/.*:\s//gp}' Alternate info retreival
