#!/bin/sh


case $1 in
    1) notify-send "🌎 Networktraffic" "🔻Traffic Recieved
🔺Traffic transmitted";;
    2) setsid -f "$TERMINAL" -e vim ~/.config/scripts/blocks/sb-nettraff ;;
    3) setsid -f "$TERMINAL" -e btop ;;
esac

